/**
 * Regenerates the structured-data block in index.html from js/data.js.
 *
 * The storefront builds its markup at runtime, so a crawler that does not run
 * scripts sees no product, no price and no answer to any question. This puts
 * the same facts into the page as JSON-LD, which every crawler reads without
 * rendering. It is generated rather than hand-kept so it cannot drift from
 * data.js — run `node tools/build-jsonld.mjs` after changing products, prices,
 * ratings or the FAQ. It is not a build step; the committed HTML is the site.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { PRODUCTS, FAQ, SHIPPING, RATING_SUMMARY, priceFor } from '../js/data.js';

const SITE = 'https://kestra.sa/';
const START = '<!-- structured data: generated by tools/build-jsonld.mjs, do not edit by hand -->';
const END = '<!-- /structured data -->';

const products = PRODUCTS.map((p) => ({
  '@type': 'Product',
  name: `KESTRA ${p.name.en}`,
  alternateName: p.name.ar,
  sku: `KESTRA-${p.index}`,
  description: `${p.flavour.en}. ${p.caffeine} mg caffeine, ${p.sugar} g sugar, 355 mL.`,
  brand: { '@type': 'Brand', name: 'KESTRA' },
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: p.rating,
    reviewCount: p.reviews,
    bestRating: 5,
  },
  offers: Object.keys(p.packs).map((packId) => ({
    '@type': 'Offer',
    name: `${packId}-can pack`,
    price: priceFor(p, packId).toFixed(2),
    priceCurrency: 'SAR',
    availability: 'https://schema.org/InStock',
    url: SITE,
    shippingDetails: {
      '@type': 'OfferShippingDetails',
      shippingRate: { '@type': 'MonetaryAmount', value: SHIPPING.fee, currency: 'SAR' },
      shippingDestination: { '@type': 'DefinedRegion', addressCountry: 'SA' },
    },
  })),
}));

const graph = [
  {
    '@type': 'WebSite',
    '@id': `${SITE}#website`,
    url: SITE,
    name: 'KESTRA',
    inLanguage: ['ar-SA', 'en-SA'],
  },
  {
    '@type': 'ItemList',
    name: 'KESTRA range',
    numberOfItems: PRODUCTS.length,
    itemListElement: products.map((p, i) => ({ '@type': 'ListItem', position: i + 1, item: p })),
  },
  {
    '@type': 'FAQPage',
    mainEntity: FAQ.map((f) => ({
      '@type': 'Question',
      name: f.q.en,
      acceptedAnswer: { '@type': 'Answer', text: f.a.en },
    })),
  },
];

const block = `${START}
<script type="application/ld+json">
${JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 1)}
</script>
${END}`;

const file = new URL('../index.html', import.meta.url);
const html = readFileSync(file, 'utf8');
const from = html.indexOf(START);
const to = html.indexOf(END);
const next =
  from !== -1 && to !== -1
    ? html.slice(0, from) + block + html.slice(to + END.length)
    : html.replace('</head>', `${block}\n</head>`);
writeFileSync(file, next);
console.log(
  `structured data written: ${PRODUCTS.length} products, ` +
    `${products.reduce((n, p) => n + p.offers.length, 0)} offers, ${FAQ.length} questions ` +
    `(rating summary ${RATING_SUMMARY.average} from ${RATING_SUMMARY.count})`
);
